Tracker:AddLocations("locations/Blossom.json")
Tracker:AddLocations("locations/Bosses.json")
Tracker:AddLocations("locations/Fall.json")
Tracker:AddLocations("locations/Forbidden Isle.json")
Tracker:AddLocations("locations/Goals.json")
Tracker:AddLocations("locations/Hills.json")
Tracker:AddLocations("locations/Lake.json")
Tracker:AddLocations("locations/Pillars.json")
Tracker:AddLocations("locations/Sky Cemetery.json")
Tracker:AddLocations("locations/Swamp.json")
Tracker:AddLocations("locations/Temple.json")
Tracker:AddLocations("locations/Overworld.json")
