Tracker:AddLocations("locations/access.json")
Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Bosses.json")
Tracker:AddLocations("locations/areas/Blossom.json")
Tracker:AddLocations("locations/areas/Fall.json")
Tracker:AddLocations("locations/areas/Forbidden.json")
Tracker:AddLocations("locations/areas/Goals.json")
Tracker:AddLocations("locations/areas/Hills.json")
Tracker:AddLocations("locations/areas/Lake.json")
Tracker:AddLocations("locations/areas/Pillar.json")
Tracker:AddLocations("locations/areas/Sky Cemetery.json")
Tracker:AddLocations("locations/areas/Swamp.json")
Tracker:AddLocations("locations/areas/Temple.json")
